--feat:: Worked on choose metamask page
idamvictor/serene pull request #14
Opened 2024-08-14 18:53 UTC by Charlie042

- Worked on the ui of the blockchain part

2024-08-14 20:28 UTC, CrownedTechie requested changes
**Do well to make these changes. _Thanks!_** @Charlie042

2024-08-14 20:28 UTC, CrownedTechie commented on src/assets/index.js
Please, do well to move all Icon imports to the allocated section for it

2024-08-14 20:28 UTC, CrownedTechie commented on src/Component/AuthFlow.jsx
You don't have to import React from 'react'

2024-08-14 20:28 UTC, CrownedTechie commented on src/icons .png
File not properly named.  I can't even locate it. Was it deleted?

<img width="196" alt="Screenshot 2024-08-14 203850" src="https://github.com/user-attachments/assets/5bd3ab27-2beb-4337-a31b-62e6b5dfbe85">

2024-08-14 20:28 UTC, CrownedTechie commented on src/assets/Icons/Communities.svg
<img width="519" alt="Screenshot 2024-08-14 205842" src="https://github.com/user-attachments/assets/e70da353-2bfb-43be-a2eb-cbf6a7ba0a71">

So the above is the same error happening here.  Do check all the latest icons you added and all the imports because I'm seeing the same error on all of them. Use the screenshot below as a guide to troubleshoot:
<img width="635" alt="Screenshot 2024-08-14 205618" src="https://github.com/user-attachments/assets/d63cb6a0-9a47-4c36-823c-412e3917fe92">

2024-08-14 20:28 UTC, CrownedTechie commented on src/Component/ui/Modal.jsx
- Remove the import React from 'react' 
- Do well to add semi-colons at the end of all operations to maintain consistency in our codebase and to prevent potential bugs

2024-08-14 20:28 UTC, CrownedTechie commented on src/assets/index.js
- You might consider removing imports that are not in use or commenting it out to keep the code clean and to help narrow down errors

2024-08-16 03:07 UTC, Charlie042 commented on src/assets/Icons/Communities.svg
I will checkk on this..

2024-08-16 03:08 UTC, Charlie042 commented on src/assets/index.js
No problem...I will check on it

2024-08-23 09:56 UTC, closed without merging